version: '3.8'

services:
  serverest:
    image: paulogoncalvesbh/serverest:latest
    container_name: serverest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3